{{- range .Values.pools }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ingest.fullname" $ }}-{{ .name }}
  labels:
    {{- include "ingest.labels" $ | nindent 4 }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      {{- include "ingest.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ingest.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- range $.Values.initContainers }}
        - name: {{ .name }}
          image: "{{ $.Values.global.registry }}{{ .image.repository }}:{{ .image.tag }}"
          {{- if .securityContext }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          {{- end }}
          {{- if .env }}
          env:
            {{- toYaml .env | nindent 12 }}
          {{- end }}
          {{- if .volumes }}
          volumeMounts:
            {{- range .volumes }}
            {{- include "common.volumeMount" . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .cmd }}
          command:
            {{- range .cmd }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if .args }}
          args:
            {{- range .args }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
      containers:
        - name: {{ $.Chart.Name }}
          workingDir: {{ $.Values.global.volumes.datawave.destination }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.global.registry }}{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- if .debug }}
          ports:
            - containerPort: {{ default 5005 .debug.port }}
          {{- end }}
          env:
            - name: "SOURCE_QUEUE"
              value: {{ .queue }}
            - name: "OUTPUT_DIR"
              value: {{ $.Values.global.volumes.output.prefix }}{{ $.Values.global.volumes.output.destination }}/{{ .name }}
            - name: "CONFIG_SERVER_URL"
              value: "http://{{ $.Values.global.services.configuration }}:8888/configserver"
            - name: "ZOOKEEPER_HOST"
              value: "{{ $.Values.global.services.zookeeper }}"
            - name: "ACCUMULO_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.accumulo.name }}
                  key: {{ $.Values.global.secrets.accumulo.username }}
                  optional: false
            - name: "ACCUMULO_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.accumulo.name }}
                  key: {{ $.Values.global.secrets.accumulo.password }}
                  optional: false
            - name: "KEYSTORE_LOCATION"
              {{/*
                  Set the keystore location from a secret if set, otherwise set from the pki destination and keystore name
              */}}
              {{- if $.Values.global.secrets.keystore.path -}}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.keystore.name }}
                  key: {{ $.Values.global.secrets.keystore.path }}
                  optional: false
              {{- else -}}
              value: "file://{{ $.Values.global.volumes.pki.destination }}/{{ default $.Values.global.volumes.pki.keystore $.Values.keystore }}"
              {{- end }}
            - name: "KEYSTORE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.keystore.name }}
                  key: {{ $.Values.global.secrets.keystore.password }}
                  optional: false
            - name: "TRUSTSTORE_LOCATION"
              {{/*
                 Set the truststore location from a secret if set, otherwise set from the pki destination and truststore name
              */}}
              {{- if $.Values.global.secrets.truststore.path -}}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.truststore.name }}
                  key: {{ $.Values.global.secrets.truststore.path }}
                  optional: false
              {{- else -}}
              value: "file://{{ $.Values.global.volumes.pki.destination }}/{{ default $.Values.global.volumes.pki.truststore $.Values.truststore }}"
              {{- end }}
            - name: "TRUSTSTORE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.truststore.name }}
                  key: {{ $.Values.global.secrets.truststore.password }}
                  optional: false
          {{- if .envOverride }}
          {{- toYaml .envOverride | nindent 12 }}
          {{- else if $.Values.env }}
          {{- toYaml $.Values.env | nindent 12 }}
          {{- end }}
          {{- if $.Values.cmd.override }}
          command:
            {{- range $.Values.cmd.override }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          args:
            {{- if not $.Values.args.replace }}
            - "--spring.output.ansi.enabled=ALWAYS"
            - "--spring.profiles.active={{ .profiles }}"
            {{- end }}
            {{- range $.Values.args.override }}
            - {{ . | quote }}
            {{- end }}
          volumeMounts:
            {{- include "common.volumeMount" $.Values.global.volumes.pki | nindent 12 }}
            {{- include "common.volumeMount" $.Values.global.volumes.hadoop | nindent 12 }}
            {{- include "common.volumeMount" $.Values.global.volumes.logs | nindent 12 }}
            {{- include "common.volumeMount" $.Values.global.volumes.datawave | nindent 12 }}
            {{- include "common.volumeMount" $.Values.global.volumes.output | nindent 12 }}
            {{- range $.Values.volumes }}
              {{- include "common.volumeMount" . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      volumes:
        {{- include "common.volume" $.Values.global.volumes.pki | nindent 8 }}
        {{- include "common.volume" $.Values.global.volumes.hadoop | nindent 8 }}
        {{- include "common.volume" $.Values.global.volumes.datawave | nindent 8 }}
        {{- range $.Values.volumes }}
          {{- include "common.volume" . | nindent 8 }}
        {{- end }}
        {{- with $.Values.global.volumes.output }}
        - name: {{ .name }}
          {{- if eq .source.type "hostPath" }}
          hostPath:
            path: {{ .source.path }}
            type: DirectoryOrCreate
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        - name: {{ $.Values.global.volumes.logs.name }}
          hostPath:
            path: {{ $.Values.global.volumes.logs.source.path }}
            type: DirectoryOrCreate
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}