{{- if $.Values.messaging.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.global.volumes.rabbit.source.name }}"
  labels:
    application: "{{ .Values.global.volumes.rabbit.source.name }}"

data:
  enabled_plugins: |
    [rabbitmq_management, rabbitmq_shovel, rabbitmq_shovel_management].

  rabbitmq.conf: |
    loopback_users.guest = false
    queue_master_locator = min-masters

  advanced.config: |
    [
      {rabbit, [
        {consumer_timeout, undefined}
      [}
    ].
{{- end }}