version: '2.2'
volumes:
  quickstart_data:
  hadoop_conf:

services:
  quickstart:
    profiles:
      - quickstart
    command: ["datawave-bootstrap.sh", "--accumulo"]
    image: datawave/quickstart-compose:3.28.0-SNAPSHOT
    environment:
      - DOCKER_HOST=quickstart
    ports:
      # resource manager web ui
      - "8088:8088"
      # node manager web ui
      - "8042:8042"
      # namenode web ui
      - "9870:9870"
      # datanode web ui
      - "9864:9864"
      # jobhistory web ui
      - "8021:8021"
      # accumulo monitor
      - "9995:9995"
    volumes:
      - hadoop_conf:/opt/datawave/contrib/datawave-quickstart/hadoop/client/conf
      - quickstart_data:/opt/datawave/contrib/datawave-quickstart/data
      - ./logs:/logs
    networks:
      - demo
    healthcheck:
      test: ["CMD-SHELL", "! accumuloStatus | grep DW-WARN > /dev/null"]

  consul:
    image: consul:1.9.8
    hostname: localhost
    environment:
      - 'CONSUL_LOCAL_CONFIG={"datacenter": "demo_dc", "disable_update_check": true, "enable_agent_tls_for_checks": true, "key_file": "/etc/pki/testServer.key", "cert_file": "/etc/pki/testServer.crt", "ca_file": "/etc/pki/testCA.pem", "verify_outgoing": true, "verify_server_hostname": false}'
      - CONSUL_BIND_INTERFACE=eth0
    # defined as host:container
    ports:
      - "8400"
      - "8500:8500"
      - "53"
    volumes:
      - ${PKI_DIR:-./pki}:/etc/pki:ro
    networks:
      - demo

  rabbitmq:
    image: rabbitmq:3.8.25-alpine
    volumes:
      - ${RABBITMQ_CONFIG_DIR:-./rabbitmq-config}:/etc/rabbitmq
      - ./logs:/logs
    environment:
      - TCP_PORTS=15672, 5672
      - RABBITMQ_ERLANG_COOKIE="mycookie"
    ports:
      - "15672:15672"
    networks:
      - demo
    depends_on:
      consul:
        condition: service_started

  zookeeper:
    image: bitnami/zookeeper:3.6.3
    ports:
      - "3181"
    networks:
      - demo
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_PORT_NUMBER=3181

  configuration:
    image: datawave/config-service:1.6-SNAPSHOT
    command:
      - --spring.output.ansi.enabled=ALWAYS
      - --spring.profiles.active=consul,native,open_actuator
      - --spring.cloud.consul.host=consul
      - --spring.cloud.config.server.native.searchLocations=file:///microservice-config
    environment:
      - 'KEYSTORE_LOCATION=file:///etc/pki/testServer.p12'
      - KEYSTORE_PASSWORD=ChangeIt
      - KEY_ALIAS=certificate
    ports:
      - "8888:8888"
    volumes:
      - ${CONFIG_DIR:-./config}:/microservice-config:ro
      - ${PKI_DIR:-./pki}:/etc/pki:ro
      - ./logs:/logs
    networks:
      - demo
    depends_on:
      rabbitmq:
        condition: service_started

  feeder:
    image: datawave/feeder-service:1.0-SNAPSHOT
    command:
      - --spring.output.ansi.enabled=ALWAYS
      - --spring.profiles.active=consul,compose
      - --spring.cloud.consul.host=consul
      - --spring.cloud.consul.discovery.instance-id=$${spring.application.name}:$${random.value}
    # debug port
    # ports:
    #  - "5005:5005"
    volumes:
      - ${PKI_DIR:-./pki}:/etc/pki:ro
      - ./logs:/logs
      - hadoop_conf:/etc/hadoop/conf
      - ./ingest-config:/etc/datawave/conf
    networks:
      - demo
    depends_on:
      rabbitmq:
        condition: service_started
      configuration:
        condition: service_started
      quickstart:
        condition: service_healthy

  ingest:
    image: datawave/ingest-service:1.0-SNAPSHOT
    command:
      - --spring.output.ansi.enabled=ALWAYS
      - --spring.profiles.active=consul,compose
      - --spring.cloud.consul.host=consul
      - --spring.cloud.consul.discovery.instance-id=$${spring.application.name}:$${random.value}
    environment:
      - ZOOKEEPER_HOST=${DW_ZOOKEEPER_HOST}
    # debug port
    # ports:
    #  - "5005:5005"
    volumes:
      - ${PKI_DIR:-./pki}:/etc/pki:ro
      - ./logs:/logs
      - hadoop_conf:/etc/hadoop/conf
      - ./ingest-config:/etc/datawave/conf
      - ./ingest-work:file:/tmp/datawave/ingest/work
    networks:
      - demo
    depends_on:
      rabbitmq:
        condition: service_started
      configuration:
        condition: service_started
      feeder:
        condition: service_started
      quickstart:
        condition: service_healthy

  bundler:
    image: datawave/bundler-service:1.0-SNAPSHOT
    command:
      - --spring.output.ansi.enabled=ALWAYS
      - --spring.profiles.active=consul,compose
      - --spring.cloud.consul.host=consul
      - --spring.cloud.consul.discovery.instance-id=$${spring.application.name}:$${random.value}
    # debug port
    # ports:
    #  - "5005:5005"
    volumes:
      - ${PKI_DIR:-./pki}:/etc/pki:ro
      - ./logs:/logs
      - hadoop_conf:/etc/hadoop/conf
      - ./ingest-work:/tmp/datawave/ingest/work
      - ./bundler-work:/tmp/datawave/bundler/work
    networks:
      - demo
    depends_on:
      ingest:
        condition: service_started
      quickstart:
        condition: service_healthy
networks:
  demo:
