{{- range .Values.feeds }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "feeder.fullname" $ }}-{{ .name }}
  labels:
    {{- include "feeder.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "feeder.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "feeder.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.global.registry }}{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- if .debug }}
          ports:
            - containerPort: {{ default 5005 .debug.port }}
          {{- end }}
          env:
            - name: "DEST_QUEUE"
              value: {{ .queue }}
            - name: "CONFIG_SERVER_URL"
              value: "http://{{ $.Values.global.services.configuration }}:8888/configserver"
            - name: KEYSTORE_LOCATION
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.keystore.name }}
                  key: {{ $.Values.global.secrets.keystore.path }}
                  optional: false
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.keystore.name }}
                  key: {{ $.Values.global.secrets.keystore.password }}
                  optional: false
            - name: TRUSTSTORE_LOCATION
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.truststore.name }}
                  key: {{ $.Values.global.secrets.truststore.path }}
                  optional: false
            - name: TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.truststore.name }}
                  key: {{ $.Values.global.secrets.truststore.password }}
                  optional: false
          args: ["--spring.output.ansi.enabled=ALWAYS", "--spring.profiles.active={{ .profile }}"]
          volumeMounts:
            {{- include "common.volumeMount" $.Values.global.volumes.pki | nindent 12 }}
            {{- include "common.volumeMount" $.Values.global.volumes.hadoop | nindent 12 }}
            {{- include "common.volumeMount" $.Values.global.volumes.logs | nindent 12 }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      volumes:
        {{- include "common.volume" $.Values.global.volumes.pki | nindent 8 }}
        {{- include "common.volume" $.Values.global.volumes.hadoop | nindent 8 }}
        - name: {{ $.Values.global.volumes.logs.name }}
          hostPath:
            path: {{ $.Values.global.volumes.logs.source.path }}
            type: DirectoryOrCreate
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
