# global overrides for all microservices
global:
  # External service links
  services:
    # REQUIRED configuration service name/endpoint
    configuration: datawave-configuration
    # REQUIRED zookeeper service name/endpoint
    zookeeper: zookeeper
  # Externally defined accumulo account secret specification
  accumulo:
    secret:
      # REQUIRED secret name containing accumulo user/password
      name: accumulo
      # REQUIRED username for accumulo user
      username: username
      # REQUIRED password for accumulo user
      password: password
  # Volume definitions
  volumes:
    # REQUIRED (Feeder/Ingest/Bundler) PKI volume
    pki:
      # PKI volume name
      name: pki
      # REQUIRED mount location for pki
      destination: /data/certs
      source:
        # REQUIRED must be one of secret/configmap/hostPath
        type: secret
        # REQUIRED with type secret or configmap
        name: datawave-certificates-secret
    # REQUIRED (Feeder/Ingest/Bundler) HADOOP config volume
    hadoop:
      # REQUIRED HADOOP config volume name
      name: hadoop
      # REQUIRED mount location for hadoop
      destination: /etc/hadoop/conf
      source:
        # REQUIRED must be one of secret/configmap/hostPath
        type: configmap
        # REQUIRED with type secret or configmap
        name: hadoop-hadoop-minikube
    # REQUIRED (Feeder/Ingest/Bundler) logs volume
    logs:
      # REQUIRED logs mount name
      name: logs
      # REQUIRED mount location for logs
      destination: /logs
      source:
        # REQUIRED must be one of secret/configmap/hostPath
        type: hostPath
        # REQUIRED when specifying hostPath, host path to mount into destination
        path: /srv/logs
    # REQUIRED (Ingest) datawave ingest volume
    datawave:
      # REQUIRED datawave-config name
      name: datawave-conf
      # REQUIRED mount location for datawave-config
      destination: /etc/datawave/conf
      source:
        # REQUIRED must be one of secret/configmap/hostPath
        type: configmap
        # REQUIRED with type secret or configmap
        name: datawave-ingest-configmap
    # REQUIRED (Ingest)
    output:
      # REQUIRED Output location volume name
      name: output
      # REQUIRED mount location for output
      destination: /output
      # REQUIRED hdfs prefix for destination
      prefix: "file://"
      source:
        # REQUIRED must be one of secret/configmap/hostPath
        type: hostPath
        # REQUIRED when specifying hostPath, host path to mount into destination
        path: /srv/data/datawave/ingest/
    # REQUIRED (Bundler)
    input:
      # REQUIRED input location volume
      name: input
      # REQUIRED mount location for input
      destination: /input
      source:
        # REQUIRED must be one of secret/configmap/hostPath
        type: hostPath
        # REQUIRED when specifying hostPath, host path to mount into destination
        path: /srv/data/datawave/ingest/

# Feeder definition
feeder:
  # Each feeder should be defined within feeds. One deployment per feed will be created
  feeds:
    # feed name
    - name: "feed1"
      # spring profiles to apply to feed1
      profile: "minikube,profile1"
      # rabbitmq queue to publish content from feed1
      queue: "fast"
    # feed name
    - name: "feed2"
      # spring profiles to apply to feed2
      profile: "minikube,profile2"
      # rabbitmq queue to publish content from feed2
      queue: "fastest"
    # feed name
    - name: "feed3"
      # spring profiles to apply to feed3
      profile: "minikube,profile3"
      # rabbitmq queue to publish content from feed3
      queue: "fastest"
# Ingest definition
ingest:
  # Each ingest pool will create a deployment with replicas
  pools:
    # ingest pool name
    - name: "speedy"
      # rabbitmq queue to read off of
      queue: "fast"
      # number of replcias in the pool
      replicas: 1
      # spring profiles to apply to speedy pool
      profiles: "minikube,profile1"
      # accumulo secret information
      accumulo:
        secret:
          # accumulo account secret name
          name: accumulo
          # accumulo accumulo secret username field
          username: username
          # accumulo user password secret password field
          password: password
    # ingest pool name
    - name: "speediest"
      # rabbitmq queue to read off of
      queue: "fastest"
      # number of replicas in the pool
      replicas: 1
      # spring profiles to apply to speediest pool
      profiles: "minikube,profile2"
      # accumulo secret information
      accumulo:
        secret:
          # accumulo account secret name
          name: accumulo
          # accumulo account secret username field
          username: username
          # accumulo user password secret password field
          password: password
# Bundler definitions
bundler:
  # true if the bundler is being used
  enabled: true
  # bundler pools will be deployed as a daemonset for each pool
  pools:
    # pri1 pool
    - name: pri1
      # spring profiles to apply to pri1 bundler
      profiles: minikube,pri1
    # pri2 pool
    - name: pri2
      # spring profiles to apply to pri2 bundler
      profiles: minikube,pri2
# if a secret is necessary for bootstrapping define it here. FOR TESTING ONLY. DO NOT USE IN PRODUCTION
secrets:
  accumulo:
    # accumulo secret name
    name: accumulo
    # accumulo username value
    username: root
    # accumulo password value
    password: root