global:
  registry: ""
  services:
    configuration: ""
    zookeeper: ""
  secrets:
    accumulo:
      name: ""
      username: "username"
      password: "password"
    keystrore:
      name: ""
      path: ""
      password: ""
      alias: ""
    truststore:
      name: ""
      path: ""
      password: ""
  volumes:
    pki:
      name:  ""
      destination: ""
      readOnly: true
      source:
        type: ""
        name: ""
    hadoop:
      name: ""
      destination: ""
      readOnly: true
      source:
        type: ""
        name: ""
    logs:
      name: ""
      destination: ""
      source:
        type: ""
        path: ""
    datawave:
      name: ""
      destination: ""
      readOnly: true
      source:
        type: ""
        name: ""
    output:
      name: ""
      destination: ""
      prefix: ""
      source:
        type: ""
        path: ""

# each pool may define
# name - pool name
# queue - name of queue to feed pool from
# replicas - number of replicas in the deployment
# profiles - the spring configuration profile names, comma delimited for each pool
# envOverride - env to use for this pool rather than .env
pools: []

image:
  repository: "datawave/ingest-service"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# environment definition to pass to deployment, should be in yaml format can be replaced by envOverride in each pool
env: []

# volumes specific to the container
volumes: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# cmd override from the image
cmd:
  override: []
# arguments override
args:
  # replace existing arguments or append
  replace: false
  override: []

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
