global:
  registry: ""
  services:
    configuration: ""
    zookeeper: ""
  secrets:
    accumulo:
      name: ""
      # only used if pool[].accumuloUsername or Values.accumuloUsername is not set
      username: "username"
      password: "password"
    keystore:
      name: ""
      # set only if using a keystore from a secret, the path secret key
      # path:
      password: ""
      alias: ""
    truststore:
      name: ""
      # set only if using a truststore from a secret , the path secret key
      # path:
      password: ""
  volumes:
    pki:
      name:  ""
      destination: ""
      readOnly: true
      # set only if not using a keystore or truststore from a secret, the keystore/truststore file names
      # keystore: ""
      # truststore: ""
      source:
        type: ""
        name: ""
    hadoop:
      name: ""
      destination: ""
      readOnly: true
      source:
        type: ""
        name: ""
    logs:
      name: ""
      destination: ""
      source:
        type: ""
        path: ""
    datawave:
      name: ""
      destination: ""
      readOnly: true
      source:
        type: ""
        name: ""
    output:
      name: ""
      destination: ""
      prefix: ""
      source:
        type: ""
        path: ""

# each pool may define
# name - pool name
# queue - name of queue to feed pool from
# replicas - number of replicas in the deployment
# profiles - the spring configuration profile names, comma delimited for each pool
# envOverride - env to use for this pool rather than .env
# accumuloUsername - override the accumuloUsername for this pod
pools: []

# overrides for keystore/truststore names within the global.volumes.pki.destination
# keystore: ""
# truststore: ""

image:
  repository: "datawave/ingest-service"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# environment definition to pass to deployment, should be in yaml format can be replaced by envOverride in each pool
env: []

# volumes specific to the container
volumes: []

# set an accumuloUsername instead of using a secret
# accumuloUsername:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# cmd override from the image
cmd:
  override: []
# arguments override
args:
  # replace existing arguments or append
  replace: false
  override: []

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Configure Filebeat Sidecar
filebeat:
  imageRepo: docker.elastic.co/beats/filebeat
  imageTag: 8.5.1
  # For Logstash Sidecar
  logstashHost: "localhost:5044"
  # For logstash Deployment in monitoring namespace
  #logstashHost: "logstash.monitoring:5044"
  logMountDirectory: "/logs"
  logRegex: "ingest*.log"
  pipelineDestDir: "conf.d"
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 0

logstash:
  enabled: true
  imageRepo: docker.elastic.co/logstash/logstash
  imageTag: 8.5.1
  pipelineDestDir: "pipeline"
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 0