{{- if .Values.enabled }}
{{- range $.Values.pools }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "bundler.fullname" $ }}-{{ .name }}
  labels:
    {{- include "bundler.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: datawave.bundler
      {{- include "bundler.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: datawave.bundler
        {{- include "bundler.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            - name: "CONFIG_SERVER_URL"
              value: "http://{{ $.Values.global.services.configuration }}:8888/configserver"
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.keystore.name }}
                  key: {{ $.Values.global.secrets.keystore.password }}
                  optional: false
            - name: TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.truststore.name }}
                  key: {{ $.Values.global.secrets.truststore.password }}
                  optional: false
          args: ["--spring.output.ansi.enabled=ALWAYS", "--spring.profiles.active={{ .profiles }}"]
          volumeMounts:
            - mountPath: {{ $.Values.global.volumes.pki.destination }}
              name: {{ $.Values.global.volumes.pki.name }}
              readOnly: true
            - mountPath: {{ $.Values.global.volumes.hadoop.destination }}
              name: {{ $.Values.global.volumes.hadoop.name }}
              readOnly: true
            - mountPath: {{ $.Values.global.volumes.logs.destination }}
              name: {{ $.Values.global.volumes.logs.name }}
            - mountPath: {{ $.Values.global.volumes.input.destination }}
              name: {{ $.Values.global.volumes.input.name }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      volumes:
        {{- with $.Values.global.volumes.pki }}
        - name: {{ .name }}
          {{- if eq .source.type "hostPath" }}
          hostPath:
            path: {{ .source.path }}
            type: Directory
          {{- else if eq .source.type "configmap" }}
          configMap:
            name: {{ .source.name }}
          {{- else if eq .source.type "secret" }}
          secret:
            secretName: {{ .source.name }}
            optional: false
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- with $.Values.global.volumes.hadoop }}
        - name: {{ .name }}
          {{- if eq .source.type "hostPath" }}
          hostPath:
            path: {{ .source.path }}
            type: Directory
          {{- else if eq .source.type "configmap" }}
          configMap:
            name: {{ .source.name }}
          {{- else if eq .source.type "secret" }}
          secret:
            secretName: {{ .source.name }}
            optional: false
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- with $.Values.global.volumes.input }}
        - name: {{ .name }}
          {{- if eq .source.type "hostPath" }}
          hostPath:
            path: {{ .source.path }}
            type: DirectoryOrCreate
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        - name: {{ $.Values.global.volumes.logs.name }}
          hostPath:
            path: {{ $.Values.global.volumes.logs.source.path }}
            type: DirectoryOrCreate
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}