{{- if .Values.enabled }}
{{- range $.Values.pools }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "bundler.fullname" $ }}-{{ .name }}
  labels:
    {{- include "bundler.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: datawave.bundler
      {{- include "bundler.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: datawave.bundler
        {{- include "bundler.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ default $.Values.global.registry $.Values.image.registry }}{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- if .debug }}
          ports:
            - containerPort: {{ default 5005 .debug.port }}
          {{- end }}
          env:
            - name: "CONFIG_SERVER_URL"
              value: "http://{{ $.Values.global.services.configuration }}:8888/configserver"
            - name: KEYSTORE_LOCATION
              {{/*
                 Set the keystore location from a secret if set, otherwise set from the pki destination and keystore name
              */}}
              {{- if $.Values.global.secrets.keystore.path -}}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.keystore.name }}
                  key: {{ $.Values.global.secrets.keystore.path }}
                  optional: false
              {{- else -}}
              value: "file://{{ $.Values.global.volumes.pki.destination }}/{{ default $.Values.global.volumes.pki.keystore $.Values.keystore | default "keystore.p12" }}"
              {{- end }}
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.keystore.name }}
                  key: {{ $.Values.global.secrets.keystore.password }}
                  optional: false
            - name: TRUSTSTORE_LOCATION
              {{/*
                 Set the truststore location from a secret if set, otherwise set from the pki destination and truststore name
              */}}
              {{- if $.Values.global.secrets.truststore.path -}}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.truststore.name }}
                  key: {{ $.Values.global.secrets.truststore.path }}
                  optional: false
              {{- else -}}
              value: "file://{{ $.Values.global.volumes.pki.destination }}/{{ default $.Values.global.volumes.pki.truststore $.Values.truststore | default "truststore.jks" }}"
              {{- end }}
            - name: TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secrets.truststore.name }}
                  key: {{ $.Values.global.secrets.truststore.password }}
                  optional: false
            {{- if .envOverride }}
            {{- toYaml .envOverride | nindent 12 }}
            {{- else if $.Values.env }}
            {{- toYaml $.Values.env | nindent 12 }}
            {{- end }}
          args: ["--spring.output.ansi.enabled=ALWAYS", "--spring.profiles.active={{ .profiles }}"]
          volumeMounts:
            {{- include "common.volumeMount" $.Values.global.volumes.pki | nindent 12 }}
            {{- include "common.volumeMount" $.Values.global.volumes.hadoop | nindent 12 }}
            {{- include "common.volumeMount" $.Values.global.volumes.logs | nindent 12 }}
            {{- include "common.volumeMount" $.Values.global.volumes.input | nindent 12 }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
        {{ if $.Values.filebeat.enabled -}}
        - name: filebeat
          image: "{{ $.Values.filebeat.imageRepo }}:{{ $.Values.filebeat.imageTag }}"
          securityContext:
            {{- toYaml $.Values.filebeat.securityContext | nindent 12 }}
          volumeMounts:
            - name: logs
              mountPath: {{ $.Values.filebeat.logMountDirectory }}
            - name: elk-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - name: filebeat-config
              mountPath: "/usr/share/filebeat/{{ $.Values.filebeat.pipelineDestDir }}"
          env:
            - name: LOCAL_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LOGSTASH_HOST
              value: "{{ $.Values.filebeat.logstashHost }}"
            - name: LOG_LOCATION_REGEX
              value: {{ printf "%s/%s" $.Values.filebeat.logMountDirectory $.Values.filebeat.logRegex }}
        {{ if $.Values.logstash.enabled -}}
        - name: logstash
          image: "{{ $.Values.logstash.imageRepo }}:{{ $.Values.logstash.imageTag}}"
          securityContext:
            {{- toYaml $.Values.logstash.securityContext | nindent 12 }}
          volumeMounts:
            - name: elk-config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: logstash-config
              mountPath: "/usr/share/logstash/{{ $.Values.logstash.pipelineDestDir }}"
        {{- end }}
        {{- end }}
      volumes:
        {{- include "common.volume" $.Values.global.volumes.pki | nindent 8 }}
        {{- include "common.volume" $.Values.global.volumes.hadoop | nindent 8 }}
        {{- with $.Values.global.volumes.input }}
        - name: {{ .name }}
          {{- if eq .source.type "hostPath" }}
          hostPath:
            path: {{ .source.path }}
            type: DirectoryOrCreate
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        - name: {{ $.Values.global.volumes.logs.name }}
          hostPath:
            path: {{ $.Values.global.volumes.logs.source.path }}
            type: DirectoryOrCreate
        {{- if $.Values.filebeat.enabled }}
        - name: elk-config
          configMap:
            name: {{ template "bundler.name" $ }}-elk
        - name: filebeat-config
          configMap:
            name: {{ template "bundler.name" $ }}-filebeat
        {{- if $.Values.logstash.enabled }}
        - name: logstash-config
          configMap:
            name: {{ template "bundler.name" $ }}-logstash
        {{- end }}
        {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}
