global:
  registry: ""
  services:
    configuration: ""
  volumes:
    pki:
      name:  ""
      destination: ""
      source:
        type: ""
        name: ""
    hadoop:
      name: ""
      destination: ""
      source:
        type: ""
        name: ""
    logs:
      name: ""
      destination: ""
      source:
        type: ""
        path: ""
    input:
      name: ""
      destination: ""
      prefix: ""
      source:
        type: ""
        path: ""

enabled: false
pools: []

image:
  repository: "datawave/bundler-service"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Configure Filebeat Sidecar
filebeat:
  # Enable Sidecar Filebeat container
  enabled: true
  imageRepo: docker.elastic.co/beats/filebeat
  imageTag: 8.7.0
  # For Logstash Sidecar
  logstashHost: "localhost:5044"
  # For logstash Deployment in monitoring namespace
  #logstashHost: "logstash.monitoring:5044"
  logMountDirectory: "/logs"
  logRegex: "ingest*.log"
  pipelineDestDir: "conf.d"
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 0

logstash:
  # Enable Sidecar Logstash Container. Requires Filebeat to be enabled.
  enabled: true
  imageRepo: docker.elastic.co/logstash/logstash
  imageTag: 8.7.0
  pipelineDestDir: "pipeline"
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 0